import { GoogleGenAI } from "@google/genai";

const MODEL_NAME = "gemini-2.5-flash-image";

export interface GenerationResult {
  imageUrl: string;
  medium: string;
}

export async function generateMarketingVisual(
  base64Image: string,
  mimeType: string,
  medium: string
): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

  const prompt = `Place the product from the provided image onto a ${medium}. 
  Ensure the product's design, logo, and overall appearance remain perfectly consistent with the original image. 
  The product should be integrated naturally into the scene with realistic lighting, shadows, and perspective. 
  The ${medium} should be the focal point of a professional marketing photograph.`;

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
}
